use_frameworks!

platform :ios, '10.0'

target 'IQTextInputViewNotification_Example' do
  pod 'IQTextInputViewNotification', :path => '../'

  target 'IQTextInputViewNotification_Tests' do
    inherit! :search_paths

    
  end
end
